steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/$PROJECT_ID/packer'
  args: [
    'build',
    '-var','region=us-central1',
    '-var','source_image_family=ubuntu-1604-lts',
    '-var','machine_type=n1-standard-1',
    '-var','zone=us-central1-c',
    '-var','project_id=$PROJECT_ID',
    '-var','image_name=test-$BUILD_ID',
    '-var','jar_file=target/hello-gcb-0.0.1-SNAPSHOT.jar',
    'packer.json'
  ]