pipeline {
    agent none

    environment {
        FOO = "bar"
    }

    stages {
        stage("echo") {
    	    agent {
    	    	kubernetes {
      		    cloud 'kubernetes'
      		    label 'ubuntupod'
      		    yamlFile 'jenkins/podspecs/ubuntu.yaml'
		        }
	        }
	        steps {
	    	    container('ubuntu') {
                    dir("/") {
                      sh "echo 'hello'"
		                }
		         }
	        }
	      }
    }
}
